version: "3.8"

services:
  app:
    build: .
    container_name: my-commerce
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm start
    restart: always

  # Service Worker (Memproses Antrian CloudAMQP)
  worker:
    build: .
    container_name: my-worker
    env_file:
      - .env
    # Menjalankan script worker kamu
    command: npx tsx worker/notif-worker.js
    restart: always
    depends_on:
      - app
